### ISSUE TITLE
Issue using with .scss/ExtractTextPlugin

### ISSUE THREAD

**Issue by darrenklein** [jantimon/iconfont-webpack-plugin#11]
Hello, thank you very much for your work on this plugin.  I'm having some trouble using it in my React app, which uses .scss rather than .css - was hoping you could offer some guidance.

First off, here's my relevant version info from `package.json`:

```
"webpack": "^3.6.0"
"postcss-loader": "^2.1.0"
```

and Node is version 6.11.1.

The relevant parts of my `webpack.config` file is set up like so:

```
const Webpack = require("webpack"),
	ExtractTextPlugin = require("extract-text-webpack-plugin"),
	IconfontWebpackPlugin = require("iconfont-webpack-plugin")

module.exports = {
    module: {
        rules: [
	    {
	        test: /\.scss$/,
		use: ExtractTextPlugin.extract({
		    fallback: "style-loader",
		    use: ["css-loader", "sass-loader", {
		        loader: "postcss-loader",
			    options: {
			        plugins: (loader) => [
				    new IconfontWebpackPlugin(loader)
				]
			    }
			}]
		    })
              }
          ]
      }
}
```

the .svg is referenced in `_icons.scss`
```
.angle-selector {
  font-icon: url('../static/images/angle-selector.svg');
}
```

But when I run my app, I get the following error:

```
Uncaught Error: Module build failed: ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" encoding="UTF-8"?>
| <svg width="15px" height="9px" viewBox="0 0 15 9" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
|     <title>angle-selector</title>

etc...
```

and the styling for the app is totally broken.  On a whim, I changed the `url` on the icon and removed the `..` so that it read
```
.angle-selector {
  font-icon: url('/static/images/angle-selector.svg');
}
```
and my app loaded fine, but when I inspected the `.angle-selector` element in the DOM, 

 ~~font-icon: url(/static/images/angle-selector.svg);~~

with an `Unknown property name` warning.

Can you offer any guidance in this situation?  Thank you very much!

**Comment by jantimon** [comment]
I am not sure but shouldn't you switch the position of the sass and the postcss loader?

**Comment by darrenklein** [comment]
Thanks for getting back to me - do mean setting it like:

    use: ["css-loader", "postcss-loader", {
        loader: "sass-loader",
	    options: {
                plugins: (loader) => [
                    new IconfontWebpackPlugin(loader)
                ]
            }
    }]

or like

    use: ["css-loader", {
        loader: "postcss-loader",
	    options: {
                plugins: (loader) => [
                    new IconfontWebpackPlugin(loader)
                ]
            }
    }, "sass-loader"]

(Sorry, Webpack is not my forte)

**Comment by jantimon** [comment]
can you please give the second version a try?
this would execute the sass loader first and the post loader second just like sass(postcss(code))
