### ISSUE TITLE
postcss-loader peer dependency should be more flexible

### ISSUE THREAD

**Issue by davidhouweling** [jantimon/iconfont-webpack-plugin#13]
At present, postcss-loader peer dependency is locked down to version `2.1.3`. However, a patch version has been released.

I believe the peer dependency should be `^2.1.3`.

Also, is there a reason why all dependencies are locked to exact versions rather than being more flexible? There is a good chance that dependencies have changed at least in a minor or patch way, and the dependencies should be flexible enough for that, so that package managers can reuse dependencies accordingly.

**Comment by jantimon** [comment]
All tests are run with the exact version to guarantee that the current version runs with the given dependencies.

But you are right for the peer dependencies e.g. `postcss-loader` we should still allow a more flexible approach  to allow users to chose the postcss loader version.

Could you please open a pull request?

**Comment by davidhouweling** [comment]
Just wondering, are you using yarn or npm version 5+? They normally have lock files, so this would hold the exact versioning for you, rather than doing it at the package.json file level.

And i'll raise a PR for the peer dependency.

**Comment by jantimon** [comment]
Ty 👍

**Comment by davidhouweling** [comment]
It's primarily so that consumer installation is faster. Let's take the hard dependency of lodash.  You presently have `4.17.5`. And now let's say in my application I have `^4.18.0`. The package manger would need to install both versions to satisfy both requirements. For server side this isn't entirely terrible, but can be quite bloated especially in larger projects. And in proper consideration, your use of lodash would be identical if you used `4.18.0` verses `4.17.5`. imagine if lodash and all its dependencies results in a size of 100mb, then it would 200mb to satisfy both requirements.

Whilst this plugin isn't for client side (and so size isn't as high of a priority in requirements) we should still take it in the same vain of a library that would be to reduce build time.
