### ISSUE TITLE
Use minor release semantic versioning

### ISSUE THREAD

**Issue by sergeymorkovkin** [jantimon/iconfont-webpack-plugin#17]
Current code uses strict dependency versions:

```
    "loader-utils": "1.1.0",
    "lodash": "4.17.5",
    "postcss": "6.0.20",
    "svg2ttf": "4.1.0",
    "svgicons2svgfont": "9.0.2",
    "ttf2woff": "2.0.1"
```

So, if I do `npm i -D postcss-loader`, NPM will install latest version postcss@6.0.22, while iconfont-webpack-plugin will need postcss@6.0.20. Code duplication for no serious reason. Same relates to other dev/prod dependencies.

**Comment by jantimon** [comment]
Closed in 2.0.0
