### ISSUE TITLE
Add fontName option to avoid random string

### ISSUE THREAD

**Issue by sergeymorkovkin** [jantimon/iconfont-webpack-plugin#18]
In my SCSS I'm using pluging as follows: 

```
...
[class^="icon-"], [class*=" icon-"] {
  font-family: iconfont-XXXXXX !important;
  ...
}

.icon-search:before {font-icon: url(img/icons/fontawesome-icons/search.svg);}
...
```

Every time after re-generating font files I need to replace that XXXXXX identifier. My recommendation is give user complete control using SCSS. For example, we could implement fontName option that would  set font-family CSS property to fixed specified string.

Am I missing something?

**Comment by sergeymorkovkin** [comment]
@jantimon First, let me thank you for a detailed explanation of your vision. This would definitely help me while posting new suggestions. I've also read the post by Kent C. from cover to cover and confess same ideas he's sharing. One thing I don't exactly understand is how this relates to an issue. I assume you're talking about a different use-case as compared to mine. But is it a bad thing to support both use-cases? I believe there is an elegant way to do this. The straight-forward approach is implement an option, but my intuition says there's a bit more to it. Now I clearly understand why you need these font-family and font-weight options. Maybe add another custom CSS-property, which is not adding them?

**Comment by sergeymorkovkin** [comment]
Even though we went off-topic here, the discussion is still constructive.

**Comment by jantimon** [comment]
The article of Kent explains the advantages of keep parts of a component very close together in the folder structure  (even if parts of them are very different).

If you take over those ides to ui development this would mean that you could have the following structure:

```
└── atoms
    └── button
        ├── button.css
        ├── button.js
        └── plus.svg
```

Removing the folder would remove everything at once and would not leave dead code/images somewhere.

**Comment by sergeymorkovkin** [comment]
@jantimon this is not contradicting this pattern you're always mentioning. But I understand your choice to stick with it. Feel free to close.
