### ISSUE TITLE
Icon is distorted compared to svg

### ISSUE THREAD

**Issue by TuxujPes** [jantimon/iconfont-webpack-plugin#25]
Hi,

This is probably a problem with transformer itself,
but maybe someone will know how to fix this issue here?

After transforming svg to font, the result seems to be sometimes very distorted when scaled up.

Left: Font    -------------    Right: SVG

<img width="284" alt="screen shot 2018-06-29 at 4 12 23 pm" src="https://user-images.githubusercontent.com/1205052/42094284-f4969ef4-7bb7-11e8-802a-e6541a177b96.png">

The problem is obvious at first glance.
Are there any options or what are possible ways to eliminate this issue?

Thanks

**Comment by jantimon** [comment]
Which version are you using?

**Comment by TuxujPes** [comment]
@jantimon that was `v2.0.0`.
Haven't seen `v3.0.0` is out - issue does not reproduce with updates

**Comment by jantimon** [comment]
Wow cool :)
