### ISSUE TITLE
Package audit lodash security issue moderate with Prototype Pollution

### ISSUE THREAD

**Issue by Kennypt** [jantimon/iconfont-webpack-plugin#33]
Hi,

Can we do a patch update of lodash version to `4.17.11`? `yarn audit` is giving a moderate security issue of `Prototype Pollution`. Thanks.
<img width="566" alt="screenshot 2019-02-13 at 18 41 25" src="https://user-images.githubusercontent.com/7289071/52736632-2efcef80-2fc2-11e9-9826-48fd1d14cd6e.png">

**Comment by danielkoch** [comment]
I created a PR for that: https://github.com/jantimon/iconfont-webpack-plugin/pull/34

**Comment by jantimon** [comment]
I don’t see why the pull request would fix this issue as the or upgraded only nyc but not lodash

**Comment by danielkoch** [comment]
Problem was a peer dependency of `nyc`:
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/755                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by jantimon** [comment]
Removed lodash
