### ISSUE TITLE
Outlined SVG is rendered with a fill

### ISSUE THREAD

**Issue by NickMckloski** [jantimon/iconfont-webpack-plugin#37]
Hello, I have an outlined SVG that is being rendered with a fill for some reason. [Here is the SVG.](https://gist.github.com/NickMckloski/df566217598b7492e060f980ff779a02#file-outlined-svg)

Here is what it is supposed to look like: 
![input](https://user-images.githubusercontent.com/10548573/58972653-09bc0900-878c-11e9-8bf1-044921a6b030.PNG)

And here is what is rendered (ignoring color):
![output](https://user-images.githubusercontent.com/10548573/58972672-12144400-878c-11e9-81d3-bcee8a074bf0.PNG)

iconfont-webpack-plugin version - 3.1.0

Any help would be appreciated, thanks!

**Comment by jantimon** [comment]
Afaik `fill="none"` is not converted correctly.

The iconfont-webpack-plugin is using https://github.com/fontello/svg2ttf to convert svgs to fonts.  
fontello has a description on svg limitations:

https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images

> Remove all fills and colors. You can probably leave black fills. In fonts, fill is defined by contour direction. Make sure that you don't have any complex rules like evenodd fills.
Remove all FAT line attributes. This is not supported by Fontello. In fonts, fat lines are drown by 2 nested contours.
Join all contours to a single outline. This is the last and the most important step. Usually editors automatically set the correct contour direction depending on nesting and black fills.
