### ISSUE TITLE
Document .svg file constraints

### ISSUE THREAD

**Issue by em** [jantimon/iconfont-webpack-plugin#9]
When I first started to use the plugin I was getting an error "Bad ppm or 14" and it took me ages to figure out the problem was that my source SVG were of 14x14px dimension.

I suspect the underlying ttf / woff libraries convert to and integer coordinate space at some point and impose a minimum size requirement. Would be useful if you added a warning to the readme.

Also note that every .svg has to have the same width/height.

Also note that small source dimensions (e.g. 32x32px) will not error out, but will suffer from jagged rounding errors in the resultant typeface and look bad.

Also note SVG masks and transforms blow up half the time. Best to avoid any masks, and flatten in your editor before exporting.

I personally ended up sizing everything to 1400x1400px so the result is evenly divided into a 14px base font size using whole em/rem units in CSS.

**Comment by jantimon** [comment]
Sure just send over a pull request 👍
